extends WFCProblem
## A [WFCProblem] for 3D wave function collapse.
class_name WFC3DProblem

class WFC3DProblemSettings extends Resource:
	@export
	var rules: WFCRules3D

	@export
	var rect: WFCAABBi

## The rules.
var rules: WFCRules3D

## The map this problem works with.
var map: Node

## Rect of a [member map] this problem should fill.
var rect: WFCAABBi

## Rect of [member map] this problem shoud write back to [member map].
## [br]
## This rect must be contained by [member rect].
## Some cells will be generated but not written back to [member map] when it doesn't match
## [member rect].
var renderable_rect: WFCAABBi

## Rect of [member map] that encloses all the area to be generated by the initial problem.
## [br]
## It either matches [member rect] (if this is an initial problem) or contains it (if this problem
## is a sub-problem of a larger problem.
var edges_rect: WFCAABBi

## Rects from [member map] that the problem should read existing solutions from.
## [br]
## This is used to pass data from previous sub-problems when a [WFCMultithreadedSolverRunner] is
## used: previous sub-problems write solutions to their [member renderable_rect]s and the later
## sub-problems should read parts of those solutions that overlap their [member rect]s to make their
## solutions consistent.
var init_read_rects: Array[WFCAABBi] = []

## Offsets between cells and their dependencies.
## [br]
## Unlike [member WFCRules3D.axes] this field also includes reverse dependencies.
var axes: Array[Vector3i] = []

## Rule matrices.
## [br]
## Unlike [member WFCRules3D.axis_matrices] this field also includes matrices for reverse
## dependencies.
## Matrices for reverse dependencies are compured as transposition of direct dependencies matrices.
## E.g. if axis is "left" and opposite axis is "right" the direct matrix for "left" axis contains
## 1 at column [code]i[/code] of row [code]j[/code] if tile [code]i[/code] is allowed to the left of
## tile [code]j[/code].
## Then reverse matrix for "right" axis should contain 1 at column [code]j[/code] of row
## [code]i[/code] to allow tile [code]j[/code] to the right of tile [code]i[/code].
var axis_matrices: Array[WFCBitMatrix] = []

var _index_coefficients: Vector3i

func _init(settings: WFC3DProblemSettings, map_: Node):
	assert(settings.rules.is_ready())
	assert(settings.rules.mapper.supports_map(map_))
	assert(settings.rect.has_volume())

	map = map_
	rules = settings.rules
	rect = settings.rect
	edges_rect = settings.rect
	renderable_rect = settings.rect

	var sizes := settings.rect.size()
	_index_coefficients = Vector3(1, sizes.x, sizes.x * sizes.y)

	for i in range(rules.axes.size()):
		axes.append(rules.axes[i])
		axis_matrices.append(rules.axis_matrices[i])

		axes.append(-rules.axes[i])
		axis_matrices.append(rules.axis_matrices[i].transpose())

## Converts a position of a cell relative to [member Rect2i.position()] of [member rect] to index of a
## variable corresponding to that cell.
func coord_to_id(coord: Vector3i) -> int:
	var t := coord * _index_coefficients
	return t.x + t.y + t.z

## Opposite of [member coord_to_id].
func id_to_coord(id: int) -> Vector3i:
	var z := id / _index_coefficients.z
	id = id % _index_coefficients.z
	var y := id / _index_coefficients.y
	var x := id % _index_coefficients.y
	return Vector3i(x, y, z)

## See [member WFCProblem.get_cell_count].
func get_cell_count() -> int:
	return rect.get_volume()

## See [member WFCProblem.get_default_domain].
func get_default_domain() -> WFCBitSet:
	return WFCBitSet.new(rules.mapper.size(), true)

func _read_from_target(abs_pos: Vector3i) -> int:
	for r in init_read_rects:
		if r.has_point(abs_pos):
			return rules.mapper.read_cell(map, abs_pos)
	return -1

## See [member WFCProblem.populate_initial_state].
func populate_initial_state(state: WFCSolverState):
	var axis_pre_edge_domains: Array[WFCBitSet] = []

	if rules.edge_domain != null:
		assert(not rules.edge_domain.is_empty())
		for m in axis_matrices:
			var pre_edge_domain := m.transform(rules.edge_domain)
			assert(not pre_edge_domain.is_empty())
			axis_pre_edge_domains.append(pre_edge_domain)

	var sz := rect.size()

	for x in range(sz.x):
		for y in range(sz.y):
			for z in range(sz.z):
				var pos: Vector3i = Vector3i(x, y, z)
				var abs_pos := rect.position() + pos

				# First try to read from target map (if point is contained in initial_read_rects)
				var from_map := _read_from_target(abs_pos)

				if from_map >= 0:
					state.set_solution(coord_to_id(pos), from_map)
				#else:
					## Otherwise - apply preconditions...
					#var domain: WFCBitSet = precondition.read_domain(abs_pos)
#
					## ...and edge conditions
					#if not axis_pre_edge_domains.is_empty():
						#for axis_id in range(len(axes)):
							#var neighbour_pos := abs_pos + axes[axis_id]
							#if not edges_rect.has_point(neighbour_pos):
								#if precondition.read_domain(neighbour_pos) == null:
									#if domain == null:
										#domain = axis_pre_edge_domains[axis_id]
									#else:
										#domain = domain.intersect(axis_pre_edge_domains[axis_id])
										#assert(not domain.is_empty())
#
					#if domain != null:
						#var bt: bool = state.set_domain(coord_to_id(pos), domain)
						#assert(not bt, "Precondition yielded an empty domain at (%f, %f, %f)" % [x, y, z])

## See [member WFCProblem.compute_cell_domain].
func compute_cell_domain(state: WFCSolverState, cell_id: int) -> WFCBitSet:
	var res: WFCBitSet = state.cell_domains[cell_id].copy()
	var pos: Vector3i = id_to_coord(cell_id)

	for i in range(axes.size()):
		var other_pos: Vector3i = pos + axes[i]

		if not rect.has_point(other_pos + rect.position()):
			continue

		var other_id: int = coord_to_id(other_pos)

		if state.cell_solution_or_entropy[other_id] == WFCSolverState.CELL_SOLUTION_FAILED:
			continue

		var other_domain: WFCBitSet = state.cell_domains[other_id]
		res.intersect_in_place(axis_matrices[i].transform(other_domain))

	return res

## See [member WFCProblem.mark_related_cells].
func mark_related_cells(changed_cell_id: int, mark_cell: Callable):
	var pos: Vector3i = id_to_coord(changed_cell_id)

	for i in range(axes.size()):
		var other_pos: Vector3i = pos + axes[i]
		if rect.has_point(other_pos + rect.position()):
			mark_cell.call(coord_to_id(other_pos))

## Renders [member renderable_rect] of current solution to the [member map].
## [br]
## Unsolved (as well as failed) cells are rendered as empty.
func render_state_to_map(state: WFCSolverState):
	assert(rect.encloses(renderable_rect))
	var mapper := rules.mapper

	var render_rect_offset: Vector3i = renderable_rect.position() - rect.position()
	var sz := renderable_rect.size()

	for x in range(sz.x):
		for y in range(sz.y):
			for z in range(sz.z):
				var local_coord: Vector3i = Vector3i(x, y, z) + render_rect_offset
				var cell: int = state.cell_solution_or_entropy[coord_to_id(local_coord)]

				if cell == WFCSolverState.CELL_SOLUTION_FAILED:
					cell = -1

				mapper.write_cell(
					map,
					local_coord + rect.position(),
					cell
				)

## Maximal distances along X and Y axes between a cell and it's immediate dependencies.
func get_dependencies_range() -> Vector3i:
	var res := Vector3i.ZERO

	for a in axes:
		res = res.max(a.abs())

	return res

## See [member WFCProblem.pick_divergence_option].
## [br]
## Accounts for [member WFCRules2D.probabilities] of [member rules] if
## [member WFCRules2D.probabilities_enabled] is set in [member rules].
func pick_divergence_option(options: Array[int]) -> int:
	if not rules.probabilities_enabled:
		return super.pick_divergence_option(options)

	assert(options.size() > 0)

	if options.size() == 1:
		return options.pop_back()

	var probabilities_sum := 0.0

	for option in options:
		probabilities_sum += rules.probabilities[option]

	var value := randf_range(0.0, probabilities_sum)
	probabilities_sum = 0
	var chosen_option := 0
	for i in range(options.size()):
		probabilities_sum += rules.probabilities[options[i]]
		if probabilities_sum > value:
			chosen_option = i
			break

	return options.pop_at(chosen_option)


# TODO: Split
# TODO: Preconditions
# TODO: AC4
